--=======================================
-- CUSTOMER SHOPPING BEHAVIOR ANALYSIS
--=======================================

-- 1. DATABASE SETUP
CREATE DATABASE customer_shopping_db;

USE customer_shopping_db;

-- 2. CREATE TABLE

CREATE TABLE customer_shopping (
    customer_id INT,
    age INT,
    gender VARCHAR(20),
    item_purchased VARCHAR(50),
    category VARCHAR(50),
    purchase_amount DECIMAL(10,2),
    location VARCHAR(50),
    size VARCHAR(10),
    color VARCHAR(30),
    season VARCHAR(20),
    review_rating DECIMAL(3,1),
    subscription_status VARCHAR(20),
    shipping_type VARCHAR(30),
    discount_applied VARCHAR(20),
    previous_purchases INT,
    payment_method VARCHAR(30),
    frequency_of_purchases VARCHAR(30),
    age_group VARCHAR(30),
    purchase_frequency_days INT
);

-- 3. IMPORT DATA
-- Data imported using MySQL Workbench
-- Table Data Import Wizard.
-- Source: customer_shopping_cleaned.csv


-- 4. DATA VERIFICATION

USE customer_shopping_db;
SELECT COUNT(*) AS total_rows FROM customer_shopping;

-- 5. DATA QUALITY CHECKS

-- Check for duplicate customer IDs
SELECT customer_id, COUNT(*) AS duplicate_count FROM customer_shopping GROUP BY customer_id HAVING COUNT(*) > 1;

-- Check for NULL values

SELECT COUNT(*) AS total_rows, COUNT(customer_id) AS customer_ids, COUNT(age) AS ages, COUNT(purchase_amount) AS purchase_amounts,COUNT(review_rating) AS review_ratings FROM customer_shopping;

-- 6. SQL ANALYSIS
-- The following queries analyze customer shopping behavior and answer key business questions using SQL.

--Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) AS total_revenue FROM customer_shopping GROUP BY gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount, discount_applied from customer_shopping where discount_applied = 'Yes' and purchase_amount > (select AVG(purchase_amount) from customer_shopping);

--Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, AVG(review_rating) AS avg_review_rating from customer_shopping group by item_purchased order by avg_review_rating desc limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, AVG(purchase_amount) AS avg_purchase_amount from customer_shopping where shipping_type in ('Standard', 'Express') group by shipping_type order by avg_purchase_amount desc;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, AVG(purchase_amount) AS avg_purchase_amount, SUM(purchase_amount) AS total_revenue from customer_shopping group by subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, count(*) AS total_count, SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS discount_count, (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)) * 100 AS discount_percentage from customer_shopping group by item_purchased order by discount_percentage desc limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

select 
    CASE 
        WHEN previous_purchases = 1 THEN 'New' 
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' 
        ELSE 'Loyal' 
    END AS customer_segment, 
COUNT(*) AS segment_count
from customer_shopping group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?

with item_counts AS (
    select category, item_purchased, count(customer_id) as total_orders, 
    ROW_NUMBER() OVER (PARTITION BY category ORDER BY count(customer_id) DESC) AS item_rank
    from customer_shopping group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders from item_counts where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, COUNT(*) AS total_customers from customer_shopping where previous_purchases > 5 group by subscription_status;

--Q10. What is the revenue contribution of each age group?

select age_group, SUM(purchase_amount) AS total_revenue from customer_shopping group by age_group order by total_revenue desc;

-- Q11. Which product categories generate the highest total revenue?

select category, SUM(purchase_amount) AS total_revenue from customer_shopping group by category order by total_revenue desc;

-- Q12. Which season has the highest total revenue and average purchase amount?

select season, SUM(purchase_amount) AS total_revenue, AVG(purchase_amount) AS avg_purchase_amount from customer_shopping group by season order by total_revenue desc;

-- Q13. What percentage of customers use each payment method?

select payment_method, COUNT(*) AS total_customers, (COUNT(*) / (SELECT COUNT(*) FROM customer_shopping)) * 100 AS percentage_of_customers from customer_shopping group by payment_method order by percentage_of_customers desc;

-- Q14. Which locations have the highest number of customers and highest total revenue?

select location, COUNT(*) AS total_customers, SUM(purchase_amount) AS total_revenue from customer_shopping group by location order by total_customers desc, total_revenue desc;

-- Q15. Does applying a discount affect the average purchase amount?

select discount_applied, COUNT(*) AS total_purchases, AVG(purchase_amount) AS avg_purchase_amount from customer_shopping group by discount_applied order by avg_purchase_amount desc;

-- Q16. Rank products by total revenue within each category.

with revenue_rank AS (
    select category, item_purchased, SUM(purchase_amount) AS total_revenue,
    RANK() OVER (PARTITION BY category ORDER BY SUM(purchase_amount) DESC) AS revenue_rank
    from customer_shopping group by category, item_purchased
)
select * from revenue_rank;
